DROP TABLE IF EXISTS ticket_relations;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS ticket_events;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS epics;
DROP TABLE IF EXISTS boards;
